public enum Function
{
    #region Manager
    ReadManagerProfile,
    UpdateManagerProfile,
    ReadManagingSupermarket,
    ReadManagingEmployeeProfile,
    ReadManagingEmployeeList,
    CreateManagingAvailablePromotions,
    ReadManagingAvailablePromotions,
    ReadManagingSupermarketSuppliers,
    ReadManagingSupermarketImportBill,
    ReadManagingSupermarketExportBill,
    ReadManagingSupermarketGoodsQuantities,
    ReadSavingPointPolicy,
    ReadManagingSupermarketRevenueOfDay,
    ReadManagingSupermarketRevenueOfMonth,
    ReadManagingSupermarketRevenueOfYear,
    #endregion

    #region Cashier
    ReadCashierProfile,
    UpdateCashierProfile,
    CreateExportBill,
    ReadExportBill,
    UpdateExportBill,
    DeleteExportBill,
    CreateImportBill,
    ReadImportBill,
    UpdateImportBill,
    DeleteImportBill,
    CreateGoods,
    ReadGoods,
    UpdateGoods,
    DeleteGoods,
    CreateAllCustomerCard,
    ReadAllCustomerCard,
    UpdateAllCustomerCard,
    DeleteAllCustomerCard,
    ReadSupermarketPromotions,
    #endregion

    #region Customer
    BuyGoods,
    ReadCustomerProfile,
    UpdateCustomerProfile,
    ReadCustomerExportBills,
    ReadCustomerCard,
    #endregion

    #region Admin
    CreateAllManagerProfile,
    ReadAllManagerProfile,
    UpdateAllManagerProfile,
    DeleteAllManagerProfile,
    CreateAllCashierProfile,
    ReadAllCashierProfile,
    UpdateAllCashierProfile,
    DeleteAllCashierProfile,
    CreateAllCustomerProfile,
    ReadAllCustomerProfile,
    UpdateAllCustomerProfile,
    DeleteAllCustomerProfile,
    CreateAllSupermarketInformation,
    ReadAllSupermarketInformation,
    UpdateAllSupermarketInformation,
    DeleteAllSupermarketInformation,
    ReadAllEmployeeList,
    AssignManagerToSupermarket,
    CreateAllSupplierList,
    ReadAllSupplierList,
    UpdateAllSupplierList,
    DeleteAllSupplierList,
    ReadAllSupermarketRevenueOfDay,
    ReadAllSupermarketRevenueOfMonth,
    ReadAllSupermarketRevenueOfYear,
    ReadAllGoods,
    ReadAllImportBill,
    ReadAllExportBill,
    UpdateSavingPointPolicy,
    ReadAllAvailablePromotions,
    #endregion
}