public enum Function
{
    #region Manager
    ReadManagerProfile,
    UpdateManagerProfile,
    ReadManagingSupermarket,
    ReadEmployeeProfile,
    ReadManagingEmployeeList,
    CreateManagingAvailablePromotions,
    ReadManagingAvailablePromotions,
    ReadSupermarketSuppliers,
    ReadSupermarketImportBill,
    ReadSupermarketExportBill,
    ReadGoodsQuantities,
    ReadSavingPointPolicy,
    ReadSupermarketRevenueOfDay,
    ReadSupermarketRevenueOfMonth,
    ReadSupermarketRevenueOfYear,
    #endregion

    #region Cashier
    ReadCashierProfile,
    UpdateCashierProfile,
    CreateExportBill,
    ReadExportBill,
    UpdateExportBill,
    DeleteExportBill,
    CreateImportBill,
    ReadImportBill,
    UpdateImportBill,
    DeleteImportBill,
    CreateGoods,
    ReadGoods,
    UpdateGoods,
    DeleteGoods,
    CreateCustomerCard,
    ReadCustomerCard,
    UpdateCustomerCard,
    DeleteCustomerCard,
    ReadSupermarketPromotions,
    ReadSavingPointPolicy,
    #endregion

    #region Customer
    BuyGoods,
    ReadSavingPointPolicy,
    ReadCustomerProfile,
    UpdateCustomerProfile,
    ReadGoods,
    ReadCustomerExportBills,
    ReadCustomerCard,
    ReadSupermarketAvailablePromotion,
    #endregion

    #region Admin
    CreateManagerProfile,
    ReadManagerProfile,
    UpdateManagerProfile,
    DeleteManagerProfile,
    CreateCashierProfile,
    ReadCashierProfile,
    UpdateCashierProfile,
    DeleteCashierProfile,
    CreateCustomerProfile,
    ReadCustomerProfile,
    UpdateCustomerProfile,
    DeleteCustomerProfile,
    CreateSupermarketInformation,
    ReadSupermarketInformation,
    UpdateSupermarketInformation,
    DeleteSupermarketInformation,
    ReadEmployeeList,
    AssignManagerToSupermarket,
    CreateSupplierList,
    ReadSupplierList,
    UpdateSupplierList,
    DeleteSupplierList,
    ReadSupermarketRevenueOfDay,
    ReadSupermarketRevenueOfMonth,
    ReadSupermarketRevenueOfYear,
    ReadAllGoods,
    ReadAllImportBill,
    ReadAllExportBill,
    ReadSavingPointPolicy,
    UpdateSavingPointPolicy,
    ReadAllAvailablePromotions,
    #endregion
}